<?php

/*
 * This file is part of the Ampersand backend framework.
 *
 */

namespace Ampersand\Rule;

use Ampersand\Misc\Settings;
use Ampersand\Plugs\MysqlDB\MysqlDB;
use Psr\Log\LoggerInterface;

/**
 * Chooses, per conjunct, how its violations are obtained at the close of a transaction
 *
 * The compiler publishes a cost profile per conjunct: the shape class of its violation
 * query, plus the tables that query reads in full. The shape fixes how the cost grows;
 * the population fixes when that growth crosses the fee of incremental maintenance. This
 * class supplies the second half — it holds the profile against the live table sizes —
 * and turns the pair into one route per conjunct. See Ampersand issue #1692 (design
 * choices DC-16 and DC-17); the corpus study behind the thresholds is issue #1690.
 *
 * The gate is off by default. With it off every conjunct keeps the integral route, which
 * is the behaviour of every release so far.
 */
class CostGate
{
    private LoggerInterface $logger;

    private MysqlDB $database;

    /**
     * Whether the gate decides at all. Off: every conjunct keeps the integral route.
     */
    private bool $enabled;

    /**
     * Whether a structurally enforced conjunct may skip its query altogether.
     *
     * Separate from $enabled because it is the one route that rests on a claim rather
     * than on a measurement: PRF-8 in the Ampersand proof register, status 'stated'.
     * Until that claim is proved, a deployment can use the rest of the gate without it.
     */
    private bool $skipStructural;

    /**
     * Row count above which a scanned table makes its query worth maintaining
     * incrementally. The corpus study measured the crossing between 12 000 and 96 000
     * rows on a wide table; 30 000 sits inside that band.
     */
    private int $scanThreshold;

    /**
     * Fraction of skipped conjuncts that is verified by running the query after all.
     *
     * The skip route asserts an empty violation set. This check confronts that assertion
     * with the database now and then, so a defect in claim PRF-8 surfaces as a logged
     * alarm instead of as a rule that silently stops holding.
     */
    private float $selfCheckRate;

    /**
     * Row count per table name, lazily read from the database and kept for the request
     *
     * @var array<string, int>|null
     */
    private ?array $tableSizes = null;

    public function __construct(Settings $settings, MysqlDB $database, LoggerInterface $logger)
    {
        $this->database = $database;
        $this->logger = $logger;
        $this->enabled = (bool)$settings->get('transactions.costGate.enabled', false);
        $this->skipStructural = (bool)$settings->get('transactions.costGate.skipStructural', false);
        $this->scanThreshold = (int)$settings->get('transactions.costGate.scanThreshold', 30000);
        $this->selfCheckRate = (float)$settings->get('transactions.costGate.selfCheckRate', 0.01);
    }

    public function isEnabled(): bool
    {
        return $this->enabled;
    }

    /**
     * The route this conjunct takes at the close of a transaction
     *
     * A conjunct without a cost profile — generated by a compiler older than the contract —
     * keeps the integral route, as does every conjunct while the gate is off.
     */
    public function route(Conjunct $conjunct): ConjunctRoute
    {
        if (!$this->enabled) {
            return ConjunctRoute::Integral;
        }

        return match ($conjunct->getCostClass()) {
            CostClass::Structural => $this->skipStructural ? ConjunctRoute::Skip : ConjunctRoute::Integral,
            CostClass::Recursive => ConjunctRoute::Incremental,
            CostClass::Anchored => ConjunctRoute::Integral,
            CostClass::Scan => $this->largestScanTable($conjunct) >= $this->scanThreshold
                ? ConjunctRoute::Incremental
                : ConjunctRoute::Integral,
            null => ConjunctRoute::Integral,
        };
    }

    /**
     * Whether this skipped conjunct is the one that gets verified against the database
     */
    public function selfCheckDue(): bool
    {
        if ($this->selfCheckRate <= 0.0) {
            return false;
        }
        if ($this->selfCheckRate >= 1.0) {
            return true;
        }

        return (mt_rand() / mt_getrandmax()) < $this->selfCheckRate;
    }

    /**
     * Report that a skipped conjunct turned out to have violations after all
     *
     * That combination refutes claim PRF-8 for this table layout, so it is logged as an
     * error: the route was wrong, and the rule it belongs to has been holding on an
     * assumption rather than on a fact.
     *
     * @param array<int, mixed> $violations
     */
    public function reportSelfCheckFailure(Conjunct $conjunct, array $violations): void
    {
        $this->logger->error(
            "Cost gate self-check failed: conjunct '{$conjunct}' is classified as structurally enforced, "
            . "but its violation query returns " . count($violations) . " violation(s). "
            . "The skip route is unsound for this model; set transactions.costGate.skipStructural to false "
            . "and report this against Ampersand claim PRF-8."
        );
    }

    /**
     * The size of the largest table this conjunct's query reads in full
     */
    private function largestScanTable(Conjunct $conjunct): int
    {
        $sizes = $this->getTableSizes();
        $largest = 0;
        foreach ($conjunct->getScanTables() as $table) {
            $largest = max($largest, $sizes[strtolower($table)] ?? 0);
        }

        return $largest;
    }

    /**
     * Row count per table, read once per request
     *
     * These are the optimizer's own estimates (information_schema.table_rows), not exact
     * counts: for InnoDB an exact count costs a full scan per table, which is precisely
     * what this gate exists to avoid. An estimate is enough to tell a table of a few
     * hundred rows from one of a hundred thousand, which is the only question asked here.
     *
     * @return array<string, int>
     */
    private function getTableSizes(): array
    {
        if ($this->tableSizes !== null) {
            return $this->tableSizes;
        }

        $this->tableSizes = [];
        try {
            $rows = $this->database->executeCustomSQLQuery(
                "SELECT LOWER(table_name) AS t, table_rows AS n FROM information_schema.tables WHERE table_schema = DATABASE()"
            );
            if (is_array($rows)) {
                foreach ($rows as $row) {
                    $this->tableSizes[(string)$row['t']] = (int)$row['n'];
                }
            }
        } catch (\Exception $e) {
            // Without sizes the gate cannot judge a scan; leaving the list empty routes
            // every scan conjunct to the integral query, which is the safe direction.
            $this->logger->warning("Cost gate could not read table sizes: " . $e->getMessage());
        }

        return $this->tableSizes;
    }
}
