# This workflow builds and pushes Ampersand prototype framework images to Docker Hub
# We want to have images for branches 'main' (latest)
# For release tags (v*), see the release.yml workflow instead
# We use a Github Action from the market place. See: https://github.com/marketplace/actions/build-and-push-docker-images
name: Build push to DockerHub
on:
  push:
    branches:
    - main

jobs:
  build-push:
    name: Build push
    runs-on: ubuntu-latest
    steps:
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          ampersandtarski/prototype-framework
        # generate Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v6
      with:
        push: true
        target: framework
        tags: ${{ steps.meta.outputs.tags }} # see meta step above
        labels: ${{ steps.meta.outputs.labels }}
