name: Continuous Integration
on:
  push:
    branches: # empty list to only trigger on branches (i.e. not tags, ..)

env:
  DOCKER_AMPERSAND_IMAGE: ampersandtarski/prototype-framework

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build
      run: docker build . --tag ${DOCKER_AMPERSAND_IMAGE}:${GITHUB_REF##*/}
  
  # https://hub.docker.com/r/jakzal/phpqa/ docker-image with a lot of php tools
  static-analyzer:
    name: PHP static analyzer
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build php-test-suite
      run: docker build -t php-test-suite tests
    
    - name: Composer install
      run: docker run --init -i --rm -v $(pwd):/project -w /project php-test-suite composer install
    
    - name: Phan static analysis
      run: docker run --init -i --rm -v $(pwd):/project -w /project php-test-suite ./lib/bin/phan
