name: CI
on:
  push:
    branches: # empty list to only trigger on branches (i.e. not tags, ..)

env:
  DOCKER_AMPERSAND_IMAGE: ampersandtarski/prototype-framework

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Don't use GITHUB_REF in docker tag, because it can be an invalid tag format (e.g. a branch that starts with #)
    - name: Build
      run: docker build . # --tag ${DOCKER_AMPERSAND_IMAGE}:${GITHUB_REF##*/}
  
  # https://hub.docker.com/r/jakzal/phpqa/ docker-image with a lot of php tools
  static-analyzer:
    name: PHP static analyzer
    needs: []
    runs-on: ubuntu-latest
    container: ampersandtarski/prototype-framework-ci-runner
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Composer install
      run: composer install --prefer-dist --no-dev --profile --optimize-autoloader --no-scripts --ignore-platform-reqs
    
    - name: Phan static analysis
      run: phan -p --color --config-file ./.phan/config.php
