name: CI
on:
  pull_request:

env:
  DOCKER_AMPERSAND_IMAGE: ampersandtarski/prototype-framework

jobs:
  regression-tests:
    name: Regression tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Don't use GITHUB_REF in docker tag, because it can be an invalid tag format (e.g. a branch that starts with #)
    - name: Build
      run: docker build --tag ${DOCKER_AMPERSAND_IMAGE}:local .

    - name: Tests
      run: >
        cd test/regression &&
        for d in */ ; do
          echo "$d" && docker buildx build --build-context test=$d .
        done

  static-analyzer:
    name: PHP static analyzer
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        # extensions: # allows to install php extensions with PECL
        tools: phan:v5.4 # allows to install other tools, see: https://github.com/shivammathur/setup-php

    - name: Install dependencies
      run: composer install --prefer-dist --no-dev --profile --optimize-autoloader --no-scripts --ignore-platform-reqs

    - name: Run Phan
      run: |
        cd backend
        phan --version
        phan -p --color --config-file .phan/config.php
