name: Frontend Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-tests.yml'

jobs:
  frontend-tests:
    name: Frontend tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        # NOTE: Make sure this Node version matches .devcontainer/Dockerfile
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Run unit tests
      run: |
        cd frontend
        npm run test -- --watch=false --ci

    - name: Upload unit test coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: frontend/coverage
        flags: frontend
        
    - name: Build Storybook
      run: |
        cd frontend
        npm run build-storybook
        
    - name: Start Storybook server
      run: |
        cd frontend
        npm run storybook &
        # Wait for Storybook to be ready
        npx wait-on http://localhost:6006 --timeout 60000
      
    - name: Run Cypress Stories tests
      run: |
        cd frontend
        npm run test:stories
        

